---
# Ansible playbook for a Node.js API app server.
#
# @author Jeff Geerling (2015).

- hosts: all
  gather_facts: yes
  sudo: yes

  vars_files: 
    - vars/main.yml

  roles:
    - marvinpinto.docker
    - williamyeh.docker-tools
    - radamanth.node-nvm-ansible

  tasks:
    - name: create the docker group and add your user
      shell: "usermod -aG docker {{ docker_user }}"
    # docker run -d -p 27017:27017 --name mongodb dockerfile/mongodb
    - name: build mongodb 
      docker_image: path="dockerfiles/mongodb/Dockerfile" name="sk/mongodb" state=build
    - name: run mongodb by docker
      docker:
        name: mongodb
        image: sk/mongodb
        state: started
        log_driver: json-file
        pull: always
        ports:
        - "27017:27017"
