---
# Ansible playbook for a Node.js API app server.
#
# @author Jeff Geerling (2015).

- hosts: all
  gather_facts: yes
  sudo: yes

  vars_files: 
    - vars/main.yml

  roles:
    - marvinpinto.docker
    - williamyeh.docker-tools
    - radamanth.node-nvm-ansible
    - bobbyrenwick.pip

  tasks:
    - name: create the docker group and add your user
      shell: "usermod -aG docker {{ docker_user }}"
    # docker run -d -p 27017:27017 --name mongodb dockerfile/mongodb

    # - name: install some apt package
    #   shell: "apt-get install libffi-dev libssl-dev"

    # - name: install some pip package
    #   shell: "pip install pyopenssl ndg-httpsclient pyasn1"
    #   
    # create data folder
    #   - mongodb
    #   - redis
    # create logs folder
    #   - mongodb
    #   - redis

    - name: install docker-py
      pip: name="docker-py"

    # build redis
    - name: build dockerfiles 
      docker_image: 
        name: "{{ item.name }}" 
        tag: "{{ item.tag }}"
        path: "/vagrant/dockerfiles/{{ item.directory }}" 
        state: build
      with_items:
        - { name: "mongodb", tag: "data", directory: "mongodb" }
        - { name: "redis", tag: "data", directory: "redis" }

    - name: run mongodb container 
      docker:
        image: mongodb:data
        name: mongodb
        state: started
        restart_policy: always
        ports:
        - "27017:27017"
        docker_api_version: 1.18

    - name: run redis container 
      docker:
        image: redis:data
        name: redis
        state: started
        restart_policy: always
        ports:
        - "6379:6379"
        docker_api_version: 1.18

